language: minimal

services:
  - 'docker'

script:
  - 'cp docker-compose.example.env docker-compose.env'
  - 'docker-compose build'

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push demolab/fahrwasser_pgbouncer:$TRAVIS_BRANCH
