language: minimal

services:
  - 'docker'

script:
  - 'docker-compose -f build.yml build'

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push demolab/fahrwasser_pgbouncer:$TRAVIS_BRANCH
