language: minimal

addons:
  apt:
    packages:
      - docker-ce

services:
  - "docker"

script:
  - docker-compose -f docker-compose.build.yml build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f docker-compose.build.yml push
