version: "3"

services:
  lqfb-core:
    image: demolab/fahrwasser_lqfb_core:${GITHUB_REF_SLUG:-local}
    build: liquidfeedback/core

  lqfb-frontend:
    image: demolab/fahrwasser_lqfb_frontend:${GITHUB_REF_SLUG:-local}
    build: liquidfeedback/frontend
