version: "3"

volumes:
  postgres_data: {}
  lqfb_config: {}

services:
  postgres:
    image: postgres:13-alpine
    env_file: docker-compose.env
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data

  lqfb-core:
    image: demolab/fahrwasser_lqfb_core:${TRAVIS_BRANCH:-latest}
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro

  lqfb-frontend:
    image: demolab/fahrwasser_lqfb_frontend:${TRAVIS_BRANCH:-latest}
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - lqfb_config:/opt/liquid_feedback_frontend/config
    ports:
      - 127.0.0.1:2812:2812

  adminer:
    image: adminer:latest
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8080:8080
