volumes:
  postgres_data: {}
  lqfb_config: {}

services:
  postgres:
    image: postgres:13-alpine
    env_file: docker-compose.env
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data

  lqfb-core:
    image: demolab/fahrwasser_lqfb_core:latest
    build: liquidfeedback/core
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro

  lqfb-frontend:
    image: demolab/fahrwasser_lqfb_frontend:latest
    build: liquidfeedback/frontend
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lqfb_config:/opt/liquid_feedback_frontend/config
    ports:
      - 127.0.0.1:2812:2812
