version: "3"

services:
  pgbouncer:
    image: demolab/fahrwasser_pgbouncer:${TAG_NAME:-dev}
    build: pgbouncer

  pgbouncer-exporter:
    image: demolab/fahrwasser_pgbouncer_exporter:${TAG_NAME:-dev}
    build: pgbouncer-exporter

  lqfb-core:
    image: demolab/fahrwasser_lqfb_core:${TAG_NAME:-dev}
    build: liquidfeedback/core

  lqfb-frontend:
    image: demolab/fahrwasser_lqfb_frontend:${TAG_NAME:-dev}
    build: liquidfeedback/frontend
