version: "3"

services:
  pgbouncer:
    image: demolab/fahrwasser_pgbouncer:${GITHUB_REF_SLUG:-dev}
    build: pgbouncer

  pgbouncer-exporter:
    image: demolab/fahrwasser_pgbouncer_exporter:${GITHUB_REF_SLUG:-dev}
    build: pgbouncer-exporter

  lqfb-core:
    image: demolab/fahrwasser_lqfb_core:${GITHUB_REF_SLUG:-dev}
    build: liquidfeedback/core

  lqfb-frontend:
    image: demolab/fahrwasser_lqfb_frontend:${GITHUB_REF_SLUG:-dev}
    build: liquidfeedback/frontend
