version: '3'

volumes:
  postgres_data: {}
  lqfb_config: {}

services:
  postgres:
    image: postgres:10-alpine
    env_file: docker-compose.env
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_data:/var/lib/postgresql/data

  postgres-exporter:
    image: wrouesnel/postgres_exporter
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9187:9187

  pgbouncer:
    build: pgbouncer
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro

  pgbouncer-exporter:
    build: pgbouncer-exporter
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - pgbouncer
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9127:9127

  lqfb-core:
    build: liquidfeedback/core
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
      - pgbouncer
    volumes:
      - /etc/localtime:/etc/localtime:ro

  lqfb-frontend:
    build: liquidfeedback/frontend
    env_file: docker-compose.env
    restart: unless-stopped
    depends_on:
      - postgres
      - pgbouncer
      - lqfb-core
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - lqfb_config:/opt/liquid_feedback_frontend/config
    ports:
      - 127.0.0.1:2812:2812

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 127.0.0.1:8080:8080

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 127.0.0.1:9001:8080
    restart: unless-stopped
