name: Docker Image CI


on:
  schedule:
    - cron: '37 0 * * 1'
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Create folder for storing images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Configure images folder for caching
        uses: actions/cache@v2
        with:
          path: /images
          key: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Build images
        run: docker-compose -f docker-compose.build.yml build

      - name: Save all docker images
        run: docker save demolab/fahrwasser_pgbouncer demolab/fahrwasser_pgbouncer_exporter demolab/fahrwasser_lqfb_core demolab/fahrwasser_lqfb_frontend -o /images/images.tar.gz


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Create folder for storing images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Configure images folder for caching
        uses: actions/cache@v2
        with:
          path: /images
          key: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}

      - name: Load docker images
        run: docker load -i /images/images.tar.gz

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy images
        run: docker-compose -f docker-compose.build.yml push
