name: Docker Image CI

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "37 0 * * 1"
  push:
    branches:
      - latest
      - main
      - master

env:
  DOCKER_BUILDKIT: 1

jobs:
  build_lqfb_core:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Create folder for images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Build image
        run: docker build -t demolab/fahrwasser_lqfb_core:${{ env.GITHUB_REF_SLUG }} liquidfeedback/core

      - name: Save image
        run: docker save demolab/fahrwasser_lqfb_core -o /images/lqfb_core.tar.gz

      - name: Cache image
        uses: actions/cache@v3
        with:
          path: /images/lqfb_core.tar.gz
          key: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}-lqfb_core

  build_lqfb_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Create folder for images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Build image
        run: docker build -t demolab/fahrwasser_lqfb_frontend:${{ env.GITHUB_REF_SLUG }} liquidfeedback/frontend

      - name: Save image
        run: docker save demolab/fahrwasser_lqfb_frontend -o /images/lqfb_frontend.tar.gz

      - name: Cache image
        uses: actions/cache@v3
        with:
          path: /images/lqfb_frontend.tar.gz
          key: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}-lqfb_frontend

  push_images:
    needs:
      - build_lqfb_core
      - build_lqfb_frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4.x

      - name: Create folder for images
        run: |
          sudo mkdir -p /images
          sudo chmod 777 /images

      - name: Load lqfb_core cache
        uses: actions/cache@v3
        with:
          path: /images/lqfb_core.tar.gz
          key: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}-lqfb_core

      - name: Load lqfb_frontend cache
        uses: actions/cache@v3
        with:
          path: /images/lqfb_frontend.tar.gz
          key: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}-lqfb_frontend

      - name: Load docker images
        run: |
          docker load -i /images/lqfb_core.tar.gz
          docker load -i /images/lqfb_frontend.tar.gz

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images
        run: docker-compose -f docker-compose.build.yml push
