name: Docker Image CI

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "37 0 * * 1"
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Demokratielabor
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push lqfb_core
        uses: docker/build-push-action@v5
        with:
          context: liquidfeedback/core
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            demolab/fahrwasser_lqfb_core:latest
            ghcr.io/demokratielabor/fahrwasser/lqfb_core:latest

      - name: Build and push lqfb_frontend
        uses: docker/build-push-action@v5
        with:
          context: liquidfeedback/frontend
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            demolab/fahrwasser_lqfb_frontend:latest
            ghcr.io/demokratielabor/fahrwasser/lqfb_frontend:latest
